export const initialRegState = {
  full_name: "",
  email: "",
  password: "",
  password_confirmation: "",
  user_type: "",
  gender: "",
  date_of_birth: "",
  education1: "",
  education1_institution: "",
  education1_major: "",
  education1_passing_year: 2014,
  education2: "",
  education2_institution: "",
  education2_major: "",
  education2_passing_year: 2014,
  education3: "",
  education3_institution: "",
  education3_major: "",
  education3_passing_year: 2016,
  education4: "Select education",
  education4_institution: "",
  education4_major: "",
  education4_passing_year: 2018,
  current_employment_type: "",
  industry: "Select Industry",
  working_since: "",
  employer_name: "",
  designation: "",
  religion: "Islam",
  height_feet: "",
  height_inches: "",
  weight: "",
  marital_status: "Divorced",
  current_country: "Bangladesh",
  current_city: "Dhaka",
  father_occupation: "",
  father_home_district: "",
  mother_occupation: "",
  mother_home_district: "",
  number_of_brothers: 0,
  number_of_sisters: 0,
  verification_type: "National ID",
  verification_img1: "",
  verification_img2: "",
};
